[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  included_files = ["prompts/**"]

[dev]
  command = "npm run dev"
  targetPort = 5173
  publish = "dist"
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 